### ISSUE TITLE
Functionality to be able to: find a specific user by name or id

### ISSUE THREAD

**Issue by StephenJayYoung** [wbyoung/admit-one#4]
We  want to be able to find a specific user by name or id, but the way in which admit-one is written, it requires that the user to be signed in before being able to access this data. 

Signing in should be required to change a profile, but not to use it.

Example:
path: example/users/steveyoung (show profile details)
path:example/users/331(id) (show profile details)

**Comment by wbyoung** [comment]
Duplicate of #2.
